# -*- coding: utf-8 -*-
"""GameSnake,Water and Gun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCXpMQvxmKMvYBMHOW-gvxPviiqkksu2
"""

import random

print("Snake is -1 and water is 0 and gun is 1")
n=input("Enter your item here.....")
n=n.lower()
if n == "snake":
    n = -1
elif n == "water":
    n = 0
elif n == "gun":
    n = 1
else:
    print("Please write the three which is mentioned here...")

comp=random.randint(-1,2)
print("Computer chose",comp)
if comp == "snake":
    comp = -1
    
elif comp == "water":
    comp = 0
    
else:
    comp = 1





if n==-1 and comp==0 :
    print("U won")
elif n==-1 and comp==1 :
    print("U loose")
elif n==0 and comp==-1 :
    print("U loose")
elif n==0 and comp==1 :
    print("U won")
elif n==1 and comp==-1 :
    print("U won")
elif n==1 and comp==0:
    print("U loose daa...")
else:
    print("Both are same")
    print("Computer chose",comp)
    n=input("Enter your item here.....")
    n=n.lower()
    if n==-1 and comp==0 :
      print("U won")
    elif n==-1 and comp==1 :
      print("U loose")
    elif n==0 and comp==-1 :
      print("U loose")
    elif n==0 and comp==1 :
      print("U won")
    elif n==1 and comp==-1 :
      print("U won")
    else:
      print("U loose daa...")

